
version: 2

sources:
  - name: jaffle_shop
    database: dbt-tutorial
    schema: jaffle_shop
    quoting:
      database: true
      schema: true
      identifier: true
    tables:
      - name: customers
      - name: orders

models:
  - name: brz_jaffle_shop__customers
    description: "Jaffle shop customers"

  - name: brz_jaffle_shop__orders
    description: "Jaffle shop orders"
